### ISSUE TITLE
[Heroku]Herokuを利用したbotの稼働

### ISSUE THREAD

**Issue by tamagoporo** [tamagoporo/Discord-bottibot#2]
PaaSを無料で利用できる[Heroku](https://jp.heroku.com/)を使い
簡単なbotならfreeプランで24時間365日永続利用できるのか調査。

**Comment by nishikawa-r** [comment]
「Heroku」の無償プランが廃止へ (´;ω;｀)
https://news.yahoo.co.jp/articles/c8b594a52c3150aef97f06b5249557168748d9ea

**Comment by tamagoporo** [comment]
Heroku無念！
